- hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: Import VPC setup Variables
      include_vars: vars/bastion_setup 

    - name: create vprofile ec2 key
      ec2_key:
        name: vprofile-key
        region: "{{ region }}"
      register: key_out


    - name: save private key into bastion-key.pem
      copy:
        content: "{{key_out.key.private_key}}"
        dest: "./bastion-key.pem"
        mode: 0600
      when: key_out.changed

    - name: create sec group fro bastion hosts
      ec2_group:
        name: Bastion-host-sg
        description: allow port 22 from everywhere and all port within Bastion-host-sg
        region: "{{ region }}"
        vpc_id: "{{  }}"
        rules: 
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr: "{{ MYIP }}"
      register: BastionSG_out

    - name: creating bastion hosts
      ec2:
        key_name: vprofile-key
        region: "{{ region }}"
        instance_type: t2.micro
        image: "{{ bastion_ami}}"
        wait: yes
        wait_timeout: 300
        instance_tags:
          Name: "Bastion_Host"
          project: vprofile
          owner: Devops
        exact_count: 1
        count_tag:
          Name: "Bastion_Host"
          project: vprofile
          owner: Devops
        group_id: "{{ BastionSG_out.group_id }}"
        vpc_subnet_id: "{{ }}"

      register: bastionhost_out