- hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: Import VPC Variables
      include_vars: vars/vpc_setup

    - name: create vprofile vpc
      ec2_vpc_net:
        name: "{{vpc_name}}"
        cidr_block: "{{vpccidr}}"
        region: "{{region}}"
        dns_support: yes
        dns_hostnames: yes
        tenancy: default
        state: "{{state}}"
      register: vpcout

    - debug:
        var: vpcout

    - name: create public subnet 1 in zone1
        ec2_vpc_net:
          vpc_id: "{{vpcout.vpc.id}}"
          cidr_block: "{{pubSub1Cidr}}"
          region: "{{region}}"
          az: "{{zone1}}"
          state: "{{state}}"
          map_public: yes
          resource_tags:
          name: vprofile-pubsub1
      register: pubsub1_out
