- hosts: localhost
  connection: local
  gather_facts: False
  tasks:
      - name: Import VPC Variables
        include_vars: vars/vpc_setup

      - name: Import Vprofile Variables
        include_vars: vars/vprostacksetup

      - name: create vprofile ec2 key
        ec2_key:
          name: vpro-key
          region: "{{ region }}"
        register: vprokey_out

      - name: save private key into bastion-key.pem
        copy:
          content: "{{vprokey_out.key.private_key}}"
          dest: "./vprokey_outkey.pem"
          mode: 0600
        when: vprokey_out.changed

      - name: create sec group for load balancer
        ec2_group:
          name: vproELB-sg
          description: allow port 80 from everywhere 
          region: "{{ region }}"
          vpc_id: "{{  }}"
          rules: 
             - proto: tcp
               from_port: 80
               to_port: 80
               cidr: "{{ 0.0.0.0/0 }}"
        register: vproELBsg_out


      - name: create sec group for vprofile stack
        ec2_group:
          name: vprostack-sg
          description: allow port 80 from everywhere 
          region: "{{ region }}"
          vpc_id: "{{  }}"
          purge_rules: no
          rules: 
             - proto: tcp
               from_port: 80
               to_port: 80
               group_id: "{{ vproELBsg_out.gorup.id }}"

             - proto: tcp
               from_port: 22
               to_port: 22
               group_id: "{{ BastionSGid}}".......

        register: vproELBsg_out