- hosts: localhost
  connection: local
  gather_facts: False
  tasks:
      - name: Import VPC Variables
        include_vars: vars/vpc_setup

      - name: Import Vprofile Variables
        include_vars: vars/vprostacksetup

      - name: create vprofile ec2 key
        ec2_key:
          name: vpro-key
          region: "{{ region }}"
        register: vprokey_out

      - name: save private key into bastion-key.pem
        copy:
          content: "{{vprokey_out.key.private_key}}"
          dest: "./vprokey_outkey.pem"
          mode: 0600
        when: vprokey_out.changed

      - name: create sec group for load balancer
        ec2_group:
          name: vproELB-sg
          description: allow port 80 from everywhere 
          region: "{{ region }}"
          vpc_id: "{{  }}"
          rules: 
             - proto: tcp
               from_port: 80
               to_port: 80
               cidr: "{{ 0.0.0.0/0 }}"
        register: vproELBsg_out


      - name: create sec group for vprofile stack
        ec2_group:
          name: vprostack-sg
          description: allow port 80 from everywhere 
          region: "{{ region }}"
          vpc_id: "{{  }}"
          purge_rules: no
          rules: 
             - proto: tcp
               from_port: 80
               to_port: 80
               group_id: "{{ vproELBsg_out.gorup.id }}"

             - proto: tcp
               from_port: 22
               to_port: 22
               group_id: "{{ BastionSGid}}".......

        register: vprostacksg_out


      - name: update sec group with its own sg id
        ec2_group:
          name: vprostack-sg
          description: allow port 80 from everywhere 
          region: "{{ region }}"
          vpc_id: "{{  }}"
          purge_rules: no
          rules: 
            - proto: all
              group_id: "{{ vprostacksg_out.group_id }}"


      - name: creating Nginx web01
        ec2:
          key_name: vpro-key
          region: "{{ region }}"
          instance_type: t2.micro
          image: "{{ nginx_ami }}"
          wait: yes
          wait_timeout: 300
          instance_tags:
            name: "web01"
            project: vprofile
            owner: devops team
          exact_count: 1
          count_tag:
            name: "web01"
            project: vprofile
            owner: devops team
          group_id: "{{ vprostacksg_out.group_id }}"
          vpc_subnet_id: "{{ privsub1id }}".......
        register: web01_out



      - name: creating tomcat app01
        ec2:
          key_name: vpro-key
          region: "{{ region }}"
          instance_type: t2.micro
          image: "{{ tomcat_ami }}"
          wait: yes
          wait_timeout: 300
          instance_tags:
            name: "app01"
            project: vprofile
            owner: devops team
          exact_count: 1
          count_tag:
            name: "app01"
            project: vprofile
            owner: devops team
          group_id: "{{ vprostacksg_out.group_id }}"
          vpc_subnet_id: "{{ privsub1id }}".......
        register: app01_out


      - name: creating memcache mc01
        ec2:
          key_name: vpro-key
          region: "{{ region }}"
          instance_type: t2.micro
          image: "{{ memcache_ami }}"
          wait: yes
          wait_timeout: 300
          instance_tags:
            name: "mc01"
            project: vprofile
            owner: devops team
          exact_count: 1
          count_tag:
            name: "mc01"
            project: vprofile
            owner: devops team
          group_id: "{{ vprostacksg_out.group_id }}"
          vpc_subnet_id: "{{ privsub1id }}".......
        register: mc01_out



      - name: creating Rabbit rmq01
        ec2:
          key_name: vpro-key
          region: "{{ region }}"
          instance_type: t2.micro
          image: "{{ rmq_ami }}"
          wait: yes
          wait_timeout: 300
          instance_tags:
            name: "rmq01"
            project: vprofile
            owner: devops team
          exact_count: 1
          count_tag:
            name: "rmq01"
            project: vprofile
            owner: devops team
          group_id: "{{ vprostacksg_out.group_id }}"
          vpc_subnet_id: "{{ privsub1id }}".......
        register: rmq01_out


      - name: creating mysql db01
        ec2:
          key_name: vpro-key
          region: "{{ region }}"
          instance_type: t2.micro
          image: "{{ mysql_ami }}"
          wait: yes
          wait_timeout: 300
          instance_tags:
            name: "db01"
            project: vprofile
            owner: devops team
          exact_count: 1
          count_tag:
            name: "db01"
            project: vprofile
            owner: devops team
          group_id: "{{ vprostacksg_out.group_id }}"
          vpc_subnet_id: "{{ privsub1id }}".......
        register: db01_out

      - debug:
          var: db01_out

          